[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npm install -g pm2"

[deploy]
startCommand = "pm2-runtime start backend/server.js -i max"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
JWT_SECRET = "843996"
MYSQL_DATABASE = "railway"
MYSQL_ROOT_PASSWORD = "avfdbAbzmtqzwczOawUgsiWzuhTzQJey"
MYSQLUSER = "root"
MYSQLPORT = "3306"
